name: Count Images Per Subsection

on:
  workflow_dispatch:  # Manual trigger

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Count images and generate data.json
        run: |
          echo "{" > data.json
          first_section=true
          for section in images/*; do
            if [ -d "$section" ]; then
              section_name=$(basename "$section")
              echo "  \"$section_name\": {" >> data.json
              first_subsection=true
              for subsection in "$section"/*; do
                if [ -d "$subsection" ]; then
                  subsection_name=$(basename "$subsection")
                  count=$(find "$subsection" -type f -iname "*.jpg" | wc -l)
                  if [ "$first_subsection" = false ]; then
                    echo "," >> data.json
                  fi
                  echo -n "    \"$subsection_name\": $count" >> data.json
                  first_subsection=false
                fi
              done
              echo "" >> data.json
              echo -n "  }" >> data.json
              if [ "$first_section" = true ]; then
                first_section=false
              else
                echo "," >> data.json
              fi
            fi
          done | tac | tac >> data.json
          echo "" >> data.json
          echo "}" >> data.json

      - name: Commit data.json
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data.json
          git commit -m 'Update image counts per subsection in data.json'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OnemanCircle/Slider-3.git HEAD:main
