name: Rename Nested Images

on:
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Rename images in subfolders
        run: |
          shopt -s nullglob
          for dir in images/*/; do
            echo "Processing $dir"
            cd "$dir"

            # Find jpg/jpeg files and limit to 20
            files=(*.jpg *.jpeg)
            files=( "${files[@]:0:20}" )

            # Rename original files to temporary names
            count=1
            for f in "${files[@]}"; do
              mv "$f" "temp_$count.jpg"
              count=$((count + 1))
            done

            # Rename temp files to 1.jpg, 2.jpg, ...
            count=1
            for f in temp_*.jpg; do
              mv "$f" "$count.jpg"
              count=$((count + 1))
            done

            cd - > /dev/null
          done

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add images
          git commit -m "Renamed images in subfolders to 1.jpg to 20.jpg"
          git push
