name: Unzip Images

on:
  workflow_dispatch:  # Manually triggered

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List all files for debug
        run: ls -R

      - name: Create images directory if not exists
        run: mkdir -p images

      - name: Safely unzip images.zip to images/
        run: |
          if [ -f uploads/images.zip ]; then
            echo "Unzipping images.zip into images/"
            unzip uploads/images.zip -d images/
          else
            echo "ERROR: uploads/images.zip not found"
            exit 1
          fi

      - name: Commit unzipped images
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add images/
          git commit -m 'Unzipped images into images/ folder'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OnemanCircle/Slider-3.git HEAD:main || echo "No changes to commit"
