name: Unzip Images

on:
  workflow_dispatch:  # Manual trigger

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create images directory if not exists
        run: mkdir -p images

      - name: Unzip images.zip to images/
        run: unzip uploads/images.zip -d images/

      - name: Commit unzipped images
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add images/
          git commit -m 'Unzipped images into images/ folder'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OnemanCircle/Slider-3.git HEAD:main || echo "No changes to commit"
